# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: News

# Model Form Field configuration
form: $/datacenterppnt/hotnews/models/news/fields.yaml

# Model Class name
modelClass: Datacenterppnt\Hotnews\Models\News

# Default redirect location
defaultRedirect: datacenterppnt/hotnews/news

# Create page
create:
    title: Create News
    redirect: datacenterppnt/hotnews/news/update/:id
    redirectClose: datacenterppnt/hotnews/news

# Update page
update:
    title: Edit News
    redirect: datacenterppnt/hotnews/news
    redirectClose: datacenterppnt/hotnews/news

# Preview page
preview:
    title: Preview News